projectVersion=1.0.0-SNAPSHOT
projectGroup=io.micronaut.test.internal
title=Micronaut Test Internal
projectDesc=Micronaut Test Internal Module. It exposes a BOM used by Micronaut Modules.
projectUrl=https://micronaut.io
githubSlug=micronaut-projects/micronaut-test-internal
developers=Graeme Rocher

org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.configuration-cache=false
org.gradle.configuration-cache.parallel=false
org.gradle.caching=true
org.gradle.parallel=true
