pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}
plugins {
    id 'io.micronaut.build.shared.settings' version '8.0.0-M18'
}

rootProject.name = 'micronaut-test-internal-parent'

include 'micronaut-test-internal-bom'

enableFeaturePreview 'TYPESAFE_PROJECT_ACCESSORS'

micronautBuild {
    importMicronautCatalog()
}
